# Generated by Django 5.2.4 on 2025-07-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=150)),
                ('cnpj', models.CharField(max_length=18)),
                ('ceo_name', models.CharField(max_length=150)),
                ('website', models.URLField(blank=True, null=True)),
                ('discount_url', models.URLField(blank=True, null=True)),
                ('group_students', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
