# Generated by Django 5.2.4 on 2025-07-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionsettings',
            name='logo_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
